### PR TITLE
QUICKFIX | Replace `{apiVersion}` in `baseURL`

### PR DESCRIPTION
**Pull request by yarilchenko**
Replace `{apiVersion}` in `baseURL` in case of `VersioningStrategy.UrlPath` and `axios.create`

### CODE REVIEW

**Comment by yarilchenko** [comment]
@Weffe Hi. Not sure that this is the best solution.

**Comment by Weffe** [comment]
@yarilchenko Thanks for the PR. Could you elaborate a little more on what this change addresses? 

If I am understanding this right, a user could have the `{apiVersion}` inside the baseUrl but it wouldn't get replaced currently?

**Comment by yarilchenko** [comment]
@Weffe correct

**Comment by yarilchenko** [comment]
@Weffe resolved conflicts (`dev` branch was updated) + added test for `baseURL` case. Can you check this PR? I need it asap.

**Comment by Weffe** [comment]
@yarilchenko I'll take a look at this later this evening! Thanks for the contributing :)

**Comment by Weffe** [comment]
@yarilchenko went ahead and an additional update so that we can just merge this in. I'll be publishing a new version with your change plus 2 other changes.

**Comment by Weffe** [comment]
@yarilchenko Please try out `v3.0.0` that includes your fix.

```
npm install axios-api-versioning@3.0.0
```

**Comment by yarilchenko** [comment]
@Weffe Hi. awesome, it works. Thank you 🎉

**Pull request merged**
